### PR TITLE
Offer SDK v4, NextJS v13 and Docker

### PR DESCRIPTION
**Pull request by KennyDizi**
- SDK v4
- NextJS v13
- Docker

### CODE REVIEW

**Comment by KennyDizi** [comment]
CleanShot 2023-08-30 at 10 40 06@2x
@1998code Pls take a look in to this PR.

**Comment by 1998code** [comment]
Thanks @KennyDizi 
Let me review this PR after I get back from the trip ❤️

**Comment by 1998code** [comment]
#### 📝 Changed routes:


| [**/**](https://dalle-2-94dy9f4jv-1998code.vercel.app/) |
|:-:|
|<a href="https://dalle-2-94dy9f4jv-1998code.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/rQItdX1WsIsd5D0GQoMJuzXaw_KiHcU1KdrzuIUGdLgcjB2qRfTxs7bUqbJK2Z3TcBjSRwhiAw3cPcPudpK4qg.png">(view full size)</a> |



And 1 other route:
- [**/api/images**](https://dalle-2-94dy9f4jv-1998code.vercel.app/api/images)



Commit fd875a61995b23f0f0e90defcc1e6d8388f98009 (https://dalle-2-94dy9f4jv-1998code.vercel.app).

**Comment by 1998code** [comment]
Merged with Thanks 🙏

**Pull request merged**
